id: IFD462208
default_language: en
source: https://www.lotsawahouse.org
initial_creation_type: web_scrap
imported: 2023-01-04 11:32:33.177557
last_modified: 2023-01-04 11:32:33.177568
source_metadata:
  collections:
  - Chokgyur Dechen Lingpa
  - Works of Tibetan Masters
bases:
  9ABF:
    title: The Lament of Rudra
    base_file: 9ABF.txt
    order: 1
copyright:
  status: Unknown
  notice: ''
